### ISSUE TITLE
buggy

### ISSUE THREAD

**Issue by stickylabdev** [swapnilrane24/Quiz#1]
broo

**Comment by swapnilrane24** [comment]
What bug are you facing?

**Comment by stickylabdev** [comment]
many things ,, i forgot about it

**Comment by swapnilrane24** [comment]
Please comment bugs you are facing, else I won't be able to help you.

**Comment by muafakul** [comment]
you cant play the game ,,thats it ,,

**Comment by stickylabdev** [comment]
sometimes happened repeating question with the options

**Comment by swapnilrane24** [comment]
Repeating questions is not a bug, the game dint had a logic to show question only once, if you take the new update in it only once each question is shown and new extra features are also added.

**Comment by stickylabdev** [comment]
thanks ,, iwill try it ,,,,,,,,,,,,and i have some suggestion ,, which is we should click some chategory or level  ,, before jump into the question ,,,,,,,,,,,,,,,,,,,,,,

**Comment by stickylabdev** [comment]
i just try it right now and thanks you did it
